version: '3.7'
services:
  mysql-student:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-student
    ports:
      - "3307:3306"    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: krishanu
      MYSQL_PASSWORD: krishanu
      MYSQL_DATABASE: student_guide  
    networks:
      - springdata
  spring-data:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: spring-data   
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - mysql-student
    networks:
      - springdata

networks:
  springdata:
  
